name: OTA-Generationd

on:
#  watch:
#    types: [started]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OLD_ROM_URL: https://android.googleapis.com/packages/ota-api/vsmart_casuarina_casuarinaopen/b17aa2972bb13f513409e051b1cc523e1cbc32a2.zip
  NEW_ROM_URL: https://android.googleapis.com/packages/ota-api/vsmart_casuarina_casuarinaopen/11522d445c92f1402ea381c5515ecd0cda68701b.zip

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@main
    
       - name: Initialization environment 
         run: |
           sudo -E apt-get update
           sudo -E apt-get install wget python python-pip python3 python3-pip
           pip3 install setuptools
           pip3 install bsdiff4
        
       - name: Clone OTA Generation Tool
         run: |
           git clone https://github.com/Pzqqt/Generic_OTA_Package_Generation_Script.git ota
  
       - name: Download ROM
         run: |
           cd ota
           wget -O old.zip $OLD_ROM_URL
           wget -O new.zip $NEW_ROM_URL
    
       - name: Make OTA Package
         run: |
           cd ota
           sudo chmod -R 755 bin
           sudo python3 mkota.py old.zip new.zip
    
       - name: Upload the OTA Package to WeTransfer
         run: |
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet ota/OTA.zip

