name: OTA-Generation

on:
  watch:
    types: [started]

env:
  OLD_ROM_URL: https://hugeota.d.miui.com/20.7.30/miui_RAPHAEL_20.7.30_2061f26e97_10.0.zip
  NEW_ROM_URL: https://hugeota.d.miui.com/20.8.4/miui_RAPHAEL_20.8.4_22b148a8c9_10.0.zip

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@main
    
       - name: Initialization environment 
         run: |
           sudo -E apt-get update
           sudo -E apt-get install wget python python-pip python3 python3-pip
           pip3 install setuptools bsdiff4
        
       - name: Clone OTA Generation Tool
         run: |
           git clone https://github.com/Pzqqt/Generic_OTA_Package_Generation_Script.git ota
  
       - name: Download ROM
         run: |
           wget -O old.zip $OLD_ROM_URL
           wget -O new.zip $NEW_ROM_URL
    
       - name: Make OTA Package
         run: |
           cd ota
           python3 mkota.py ~/old.zip ~/new.zip
    
       - name: Upload the OTA Package to WeTransfer
         run: |
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet ~/ota/OTA.zip

